name: Deployment pipeline BlogList
on:
  push:
    branches:
      - master
jobs:
  Deploy_fly_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    concurrency: deploy-group
    if: ${{ (github.event_name == 'push')  && (!contains(github.event.head_commit.message, '#skip')) }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies 
        run: npm install 
      - name: build and deploy
        run: npm run build
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_KEY }}
  Deploy_fly_fronend:
    needs: [Deploy_fly_backend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    concurrency: deploy-group
    if: ${{ (github.event_name == 'push')  && (!contains(github.event.head_commit.message, '#skip')) }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies 
        run: npm install
      - name: build and deploy
        run: npm run build
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_KEY }}